import { noteFromText } from "./draftUtils";
import { Project, Heading, Todo } from "../types";
import { generateId } from "./generateId";


export let getIntroList = () : Project => {
    let layout = introListLayout.map((item) => item.type==="todo" ? item._id : item);

    return {    
        _id : generateId(),    
        type : "project",  
        name : "Intro List",  
        priority : 1,
        deleted : undefined,
        description : noteFromText(`This project shows you everything you need to know to hit the ground running. Don't hesistate to play around in it - you can always create a new one from the help menu.`), 
        created : new Date(),
        deadline : null,
        completed : null,
        layout : layout as any,     
        attachedTags : [],
        hide:['next'] 
    };
};        

export const introListLayout : (Todo | Heading)[] = [
    {
        type : "heading", 
        priority:1,
        title : "Learn the basics", 
        _id : generateId(), 
        key : "Learn the basics"
    }, 
    {
        type:"todo",
        category:"project",
        title:"Click this task",
        priority:2,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Create a new task",
        priority:3,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Plan this task for later",
        priority:4,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Create new heading",
        priority:5,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Create a project",
        priority:6,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"You're done",
        priority:7,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type : "heading", 
        priority:8,
        title : "Tune your setup", 
        _id : generateId(),
        key : "Tune your setup"
    }, 
    {
        type:"todo",
        category:"project",
        title:"Show your calendar events",
        priority:9,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Enable the today widget",
        priority:10,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Sync your devices",
        priority:11,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type : "heading", 
        priority:12,
        title : "Boost your productivity", 
        _id : generateId(), 
        key : "Boost your productivity"
    },
    {
        type:"todo",
        category:"project",
        title:"Add task from anywhere",
        priority:13,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    }, 
    {
        type:"todo",
        category:"project",
        title:"Link to emails, files, and web pages",
        priority:14,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    }, 
    {
        type:"todo",
        category:"project",
        title:"Search and navigate with Quick Find",
        priority:15,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Tag your task",
        priority:16,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Go step by step with checklists",
        priority:17,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Add a reminder so you won't forget",
        priority:18,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Plan your evening",
        priority:19,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Hide the sidebar to focus on your work",
        priority:20,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Open multiple windows",
        priority:21,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null, 
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Convert a task into a project",
        priority:22,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Make your task repeat",
        priority:23,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },            
    {
        type : "heading", 
        priority:24,
        title : "Before you go...", 
        _id : generateId(), 
        key : "Before you go..."
    },
    {
        type:"todo",
        category:"project",
        title:"Any questions ? We're here to help!",
        priority:25,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    }
];