import { noteFromText } from "./draftUtils";
import { Project, Heading, Todo } from "../types";
import { generateId } from "./generateId";


export let getIntroList = () : Project => {
    let layout = introListLayout.map((item) => item.type==="todo" ? item._id : item);

    return {    
        _id : generateId(),    
        type : "project",  
        name : "Introduction (Click here to start)",  
        priority : 1,
        deleted : undefined,
        description : noteFromText(`This project gives you a quick introduction to the most important functionalities of tasklist. Just play around – you won’t break anything ☺`), 
        created : new Date(),
        deadline : null,
        completed : null,
        layout : layout as any,     
        attachedTags : [],
        hide:['next'] 
    };
};        

export const introListLayout : (Todo | Heading)[] = [
    {
        type : "heading", 
        priority:1,
        title : "Getting started", 
        _id : generateId(), 
        key : "Getting started"
    }, 
    {
        type:"todo",
        category:"project",
        title:"Click this task",
        priority:2,
        note:noteFromText("Click the box to mark this task as done."),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Create a new task",
        priority:3,
        note:noteFromText("Click on “New Task” above and enter a new task. Hit enter when finished."),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Plan this task for later",
        priority:4,
        note:noteFromText("Click on the calendar icon to schedule this task for later. It will then appear in “Upcoming” under the selected date and in “Today” as soon as the selected date has come."),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Schedule a deadline for this task",
        priority:5,
        note:noteFromText(`Click on the flag icon to set a deadline for this task. It will show you how many days are left so nothing gets lost.
The difference between scheduling a date and setting a deadline? You can schedule the task before a final deadline, so you have enough time to finish it.`),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Create a new heading",
        priority:6,
        note:noteFromText(`Click on the “…” above and select “Add heading”. By using headings, you can group tasks within a project.`),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Create a new project",
        priority:7,
        note:noteFromText("Click on the (+) in the bottom left corner and select “New Projects”. By using projects, you can collect tasks, that you need to accomplish in order to achieve a specific goal."),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"You are done",
        priority:7,
        note:noteFromText(""),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type : "heading", 
        priority:8,
        title : "Becoming a tasklist professional", 
        _id : generateId(),
        key : "Becoming a tasklist professional"
    }, 
    {
        type:"todo",
        category:"project",
        title:"Add tasks from anywhere",
        priority:9,
        note:noteFromText("Press Ctrl+Alt+T to add tasks from anywhere, without opening tasklist every time."),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Use checklists",
        priority:10,
        note:noteFromText("Click the checklist icon in a task to add a checklist for this task and add sub tasks."),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Use tags for better filtering",
        priority:11,
        note:noteFromText("Using the tag icon in a task and select or add a tag. Using tags makes it easier to find tasks, that are related to each other."),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },
    {
        type:"todo",
        category:"project",
        title:"Add a reminder to a task",
        priority:13,
        note:noteFromText("Activate a reminder for a task by clicking the calendar icon and select “Add reminder”."),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    }, 
    {
        type:"todo",
        category:"project",
        title:"Show your calendar events",
        priority:14,
        note:noteFromText(`Open the settings and go to “Calendar”. Add the URL of a calendar (*.ics) and the events of that calendar will show up in “Today” and “Upcoming”.`),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    },     
    {
        type : "heading", 
        priority:24,
        title : "That’s it", 
        _id : generateId(), 
        key : "That’s it"
    },
    {
        type:"todo",
        category:"project",
        title:"Any questions? Get in touch!",
        priority:25,
        note:noteFromText("Please check our help topics or contact our support."),
        checklist:[],
        reminder:null,
        attachedTags:[],
        deadline:null,
        created:new Date(),
        deleted:null,
        attachedDate:null,
        completedSet:null,
        completedWhen:null,
        _id:generateId()
    }
];